build_dplay:
  image: "registry.gitlab.com/moralbacteria/diablo-prdemo-patches/dplay_build:latest"
  stage: build
  script:
    - cd 00_dplay
    - mkdir build
    - cd build
    - "PRDE_VERSION=\"v${CI_COMMIT_TAG}\""
    - "[ \"${PRDE_VERSION}\" = \"v\" ] && PRDE_VERSION=\"${CI_COMMIT_SHORT_SHA}\""
    - "cmake .. -DCMAKE_TOOLCHAIN_FILE=../mingw.toolchain.cmake -DCMAKE_BUILD_TYPE=Release -DPRDE_VERSION=\"${PRDE_VERSION}\""
    - make -j $(nproc)
  artifacts:
    paths:
      - 00_dplay/build/dplay.dll
  except:
    - pages

package:
  image: "registry.gitlab.com/moralbacteria/diablo-prdemo-patches/package:latest"
  stage: deploy
  dependencies:
    - build_dplay
  script:
    - curl -L "https://github.com/footballhead/diablo-ddrawwrapper/releases/download/v0.1.0/ddrawwrapper-prde-v0.1.0.zip" > ddrawwrapper.zip
    - unzip ddrawwrapper.zip -d ddrawwrapper
    - cp ddrawwrapper/ddraw.dll /root/DIABLO/
    - cp _DOCS/README.txt /root/DIABLO/
    - cp 00_dplay/build/dplay.dll /root/DIABLO/
    - cd 02_missing_gfx
    - find levels/ -type f | mpqadd /root/DIABLO/DIABDAT.MPQ
    - find monsters/ -type f | mpqadd /root/DIABLO/DIABDAT.MPQ
    - find plrgfx/ -type f | mpqadd /root/DIABLO/DIABDAT.MPQ
    - cd ..
    - mv /root/DIABLO .
  artifacts:
    name: "pre-ablo_${CI_COMMIT_TAG}_${CI_COMMIT_SHORT_SHA}"
    paths:
      - DIABLO/
  except:
    - pages
