mpqadd:
  image: "ubuntu:latest"
  stage: build
  script:
    - DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install --no-install-recommends -y g++ make cmake zlib1g-dev libbz2-dev
    - cd diabutil
    - mkdir build
    - cd build
    - cmake ..
    - make -j$(nproc)
  artifacts:
    paths:
      - diabutil/build/mpqadd/mpqadd
      - diabutil/build/mpqextract/mpqextract
  except:
    - pages
  variables:
    GIT_SUBMODULE_STRATEGY: recursive

dplay:
  image: "registry.gitlab.com/moralbacteria/diablo-prdemo-patches/dplay_build:latest"
  stage: build
  script:
    - cd dplay
    - mkdir build
    - cd build
    - "PRDE_VERSION=\"v${CI_COMMIT_TAG}\""
    - "[ \"${PRDE_VERSION}\" = \"v\" ] && PRDE_VERSION=\"${CI_COMMIT_SHORT_SHA}\""
    - "cmake .. -DCMAKE_TOOLCHAIN_FILE=../mingw.toolchain.cmake -DCMAKE_BUILD_TYPE=Release -DPRDE_VERSION=\"${PRDE_VERSION}\""
    - make -j $(nproc)
  artifacts:
    paths:
      - dplay/build/dplay.dll
  except:
    - pages

package:
  image: "ubuntu:latest"
  stage: deploy
  script:
    - DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install --no-install-recommends -y curl p7zip unzip ca-certificates
    - curl -L "https://drive.google.com/uc?export=download&id=1E-AC21QMiOao8hVun-McROsfYBeEW20y" > prereleasedemo.7z
    - 7zr x prereleasedemo.7z
    - mkdir mpq_staging
    - cd mpq_staging
    - cat ../tools/listfile.txt | ../diabutil/build/mpqextract/mpqextract ../DIABLO/DIABDAT.MPQ
    - for dir in $(cd ../missing_gfx/ && ls -d */); do cp -R "../missing_gfx/$dir" .; done
    - for dir in *; do find "$dir" -type f >> new_listfile.txt; done
    - cat new_listfile.txt | ../diabutil/build/mpqadd/mpqadd DIABDAT.MPQ
    - cd ..
    - mv DIABLO PRE-ABLO
    - curl -L "https://github.com/footballhead/diablo-ddrawwrapper/releases/download/v0.1.0/ddrawwrapper-prde-v0.1.0.zip" > ddrawwrapper.zip
    - unzip ddrawwrapper.zip -d ddrawwrapper
    - cp mpq_staging/DIABDAT.MPQ PRE-ABLO/
    - cp ddrawwrapper/ddraw.dll PRE-ABLO/
    - cp docs/README.txt PRE-ABLO/
    - cp dplay/build/dplay.dll PRE-ABLO/
  artifacts:
    name: "pre-ablo_${CI_COMMIT_TAG}_${CI_COMMIT_SHORT_SHA}"
    paths:
      - PRE-ABLO/
  except:
    - pages
