image: "moralbacteria/diablo-prdemo-patches:latest"

build:
  script:
    - cp _DOCS/README.txt /root/DIABLO/
    - cp 00_dplay/dplay.dll /root/DIABLO/
    - cd 02_missing_gfx
    - find levels/ -type f | mpqadd /root/DIABLO/DIABDAT.MPQ
    - find monsters/ -type f | mpqadd /root/DIABLO/DIABDAT.MPQ
    - find plrgfx/ -type f | mpqadd /root/DIABLO/DIABDAT.MPQ
    - cd ..
    - vcdiff decode --dictionary /root/DIABLO/DIABLO.EXE --delta fullgame/diablo.exe.vcdiff --target /root/DIABLO/DIABLO.EXE
    - vcdiff decode --dictionary /root/DIABLO/DIABLO.EXE --delta infraring_fix/diablo.exe.vcdiff --target /root/DIABLO/DIABLO.EXE
    - vcdiff decode --dictionary /root/DIABLO/DIABLO.EXE --delta always_load_flare/diablo.exe.vcdiff --target /root/DIABLO/DIABLO.EXE
    - vcdiff decode --dictionary /root/DIABLO/DIABLO.EXE --delta snake_frame_fix/diablo.exe.vcdiff --target /root/DIABLO/DIABLO.EXE
    - vcdiff decode --dictionary /root/DIABLO/DIABLO.EXE --delta no_tp_light/diablo.exe.vcdiff --target /root/DIABLO/DIABLO.EXE
    - vcdiff decode --dictionary /root/DIABLO/DIABLO.EXE --delta hell_automap/diablo.exe.vcdiff --target /root/DIABLO/DIABLO.EXE
    - vcdiff decode --dictionary /root/DIABLO/DIABLO.EXE --delta undead_crown/diablo.exe.vcdiff --target /root/DIABLO/DIABLO.EXE
    - vcdiff decode --dictionary /root/DIABLO/DIABLO.EXE --delta tp_setlvl_fix/diablo.exe.vcdiff --target /root/DIABLO/DIABLO.EXE
    - vcdiff decode --dictionary /root/DIABLO/DIABLO.EXE --delta too_much_hp_crash/diablo.exe.vcdiff --target /root/DIABLO/DIABLO.EXE
    - vcdiff decode --dictionary /root/DIABLO/DIABLO.EXE --delta thunder-demon-missile-fix/diablo.exe.vcdiff --target /root/DIABLO/DIABLO.EXE
    - vcdiff decode --dictionary /root/DIABLO/DIABLO.EXE --delta mega_fix/diablo.exe.vcdiff --target /root/DIABLO/DIABLO.EXE
    - vcdiff decode --dictionary /root/DIABLO/DIABLO.EXE --delta stone-curse-missile-fix/diablo.exe.vcdiff --target /root/DIABLO/DIABLO.EXE
    - mv /root/DIABLO .
  artifacts:
    name: "prdemo_enhanced_$CI_COMMIT_SHORT_SHA"
    paths:
      - DIABLO/
