mpqadd:
  image: "ubuntu:latest"
  stage: build
  script:
    - DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install --no-install-recommends -y g++ make cmake zlib1g-dev libbz2-dev
    - cd diabutil
    - mkdir build
    - cd build
    - cmake ..
    - make -j$(nproc)
  artifacts:
    paths:
      - diabutil/build/mpqadd/mpqadd
      - diabutil/build/mpqextract/mpqextract
  except:
    - pages
  variables:
    GIT_SUBMODULE_STRATEGY: recursive

dplay:
  image: "registry.gitlab.com/moralbacteria/diablo-prdemo-patches/dplay_build:latest"
  stage: build
  script:
    - cd dplay
    - mkdir build
    - cd build
    - "PRDE_VERSION=\"v${CI_COMMIT_TAG}\""
    - "[ \"${PRDE_VERSION}\" = \"v\" ] && PRDE_VERSION=\"${CI_COMMIT_SHORT_SHA}\""
    - "cmake .. -DCMAKE_TOOLCHAIN_FILE=../mingw.toolchain.cmake -DCMAKE_BUILD_TYPE=Release -DPRDE_VERSION=\"${PRDE_VERSION}\""
    - make -j $(nproc)
  artifacts:
    paths:
      - dplay/build/dplay.dll
  except:
    - pages

reset_dungeon:
  image: "registry.gitlab.com/moralbacteria/diablo-prdemo-patches/dplay_build:latest"
  stage: build
  script:
    - cd reset_dungeon
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_TOOLCHAIN_FILE=../dplay/mingw.toolchain.cmake -DCMAKE_BUILD_TYPE=Release
    - make -j $(nproc)
  artifacts:
    paths:
      - reset_dungeon/build/reset_dungeon.exe
  except:
    - pages

package:
  # This is an official conan image. We only use it for conan (not GCC)
  # TODO: We could probably create a custom alpine with just conan installed...
  image: "conanio/gcc11-ubuntu16.04"
  stage: deploy
  script:
    # Get pre-release demo and ddraw.dll, put in ./PRE-ABLO via conan imports
    - conan remote add gitlab https://gitlab.com/api/v4/projects/18183220/packages/conan 
    - conan install ./ci
    # Create pre-ablo.mpq (for load_mpq_customizations)
    - cd assets
    - ./package.sh pre-ablo.mpq
    - cd ..
    # Put everything in destination folder (./PRE-ABLO)
    - cp assets/pre-ablo.mpq PRE-ABLO/
    - cp docs/README.txt PRE-ABLO/
    - cp dplay/build/dplay.dll PRE-ABLO/
    - cp reset_dungeon/build/reset_dungeon.exe PRE-ABLO/
  artifacts:
    name: "pre-ablo_${CI_COMMIT_TAG}_${CI_COMMIT_SHORT_SHA}"
    paths:
      - PRE-ABLO/
  except:
    - pages
