#ifndef __DEFINES_H__
#define __DEFINES_H__

#include <windows.h>

#define MAXQUESTS 10
#define MAX_PLRS 4
#define MAXMONSTERS 200
#define MAX_SPELLS 29
#define MAXOBJECTS 127
#define MAXDUNX 112
#define MAXDUNY 112
#define MAXTILES 2048
#define NUM_INV_GRID_ELEM 40

#define WM_DIABPAINT WM_USER

#define SCREEN_WIDTH 640
#define SCREEN_HEIGHT 480
#define SCREEN_BPP 8

#define BORDER_LEFT 64
#define BORDER_TOP 160
#define BORDER_RIGHT 64
#define BORDER_BOTTOM 16

#define SCREEN_X BORDER_LEFT
#define SCREEN_Y BORDER_TOP

#define BUFFER_WIDTH (BORDER_LEFT + SCREEN_WIDTH + BORDER_RIGHT)
#define BUFFER_HEIGHT (BORDER_TOP + SCREEN_HEIGHT + BORDER_BOTTOM)

#define SCREENXY(x, y) ((x) + SCREEN_X + ((y) + SCREEN_Y) * BUFFER_WIDTH)

#endif