#pragma once

void always_load_flare_main();
void automap_fix_main();
void cheat_main();
void devmode_main();
void fullgame_main();
void infraring_fix_main();
void max_monsters_main();
void mega_fix_main();
void music_nompq_fix_main();
void savegame_patch_fix_main();
void skip_intros_main();
void snake_frame_fix_main();
void stone_curse_missile_fix_main();
void thunder_demon_missile_fix_main();
void too_much_hp_crash_main();
void tp_setlevel_fix_main();
void undead_crown_main();
void version_override_main();
void window_main();
